<?php

namespace Ansistrano\Composer;

use Composer\Composer;
use Composer\Installer\PluginInstaller;
use Composer\IO\IOInterface;
use Composer\Package\PackageInterface;
use Composer\Repository\InstalledRepositoryInterface;

class CustomInstaller extends PluginInstaller
{
    public function __construct(IOInterface $io, Composer $composer)
    {
        parent::__construct($io, $composer);
    }

    public function supports($packageType)
    {
        return parent::supports($packageType); // TODO: Change the autogenerated stub
    }

    public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        parent::install($repo, $package); // TODO: Change the autogenerated stub
    }

    public function update(InstalledRepositoryInterface $repo, PackageInterface $initial, PackageInterface $target)
    {
        parent::update($repo, $initial, $target); // TODO: Change the autogenerated stub
    }
}
